services:
  postgres:
    image: postgres:16-alpine
    container_name: agro-postgres
    environment:
      POSTGRES_DB: agrogestao
      POSTGRES_USER: agrogestao
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - agro_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agrogestao -d agrogestao"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  agro_pg_data:
