spring.application.name=agrogestao-api

server.port=${PORT:8080}

api.security.token.secret=${JWT_SECRET}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.cors.allowed-origins=${FRONTEND_URL:https://sistema-agropecuaria-web.onrender.com}