spring.application.name=demo
api.security.token.secret=${JWT_SECRET:my-secret-key}
# A chave secreta do JWT (que já havíamos colocado)
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}

# Configurações do banco de dados em memória H2
spring.datasource.url=jdbc:h2:mem:agropecuariadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Pede para o Spring criar a tabela 'users' automaticamente baseado na nossa classe User
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update