spring.application.name=demo
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}

# Configuracoes do banco de dados em memoria H2
spring.datasource.url=jdbc:h2:mem:agropecuariadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cria a tabela users automaticamente com base na classe User
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
